---
version: '3'
services:
  shark-db:
    image: gctoutin/sharkdb:latest
    container_name: shark-db
    ports:
      - 6413:6379
    volumes:
      - ../data/redis.conf:/data/redis.conf

  shark-api:
    image: gctoutin/sharkapi:latest
    build: .
    container_name: shark-api
    environment:
      - REDIS_IP=shark-db
      - FLASK_ENV = "test"
      - FLASK_APP = "api.py"
    ports:
      - 5033:5000
    depends_on:
      - shark-db
    volumes:
      - ../sharkattacks.json:/app/sharkattacks.json

  shark-wrk:
    image: gctoutin/sharkwrk:latest
    build: .
    container_name: shark-wrk
    environment:
      - REDIS_IP=shark-db
    depends_on:
      - shark-db
