FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get install -y python-pip python-dev build-essential
COPY requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt
COPY /src/api.py /app/
ENV FLASK_APP="api.py"
ENV FLASK_ENV="test"
ENV REDIS_IP=127.0.0.1
ENTRYPOINT ["python"]
CMD ["api.py"]
