---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shark-pvc
  labels:
    app: shark-pvc
    username: gctoutin
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
